feat(dashboard): gh #602 Added cluster banner + updated look and feel for delete button
hmdc/sid2 pull request #36
Opened 2021-12-20 16:23 UTC by adaybujeda

Added cluster banner to the home page when no sessions are running.
Updated delete session button to make it less prominent.

Part of the UI improvements after the first deployment to the FASSE cluster.

2022-01-05 19:12 UTC, whorka requested changes
This implementation hard-codes configuration values which are site-specific. Please retool the logic to load the `sid_welcome_message` HTML from a configuration file instead (to be delivered via the `docker compose` step in the `Makefile` in the Local Development and Remote Development environments; and to be delivered by Puppet in the Staging and Production environments).

In general, we should avoid hard-coding site-specific values, since this project is intended to be open source, and will be publicized to the wider OOD user community on Thursday.

2022-01-05 19:13 UTC, whorka commented on dashboard/application/app/assets/stylesheets/quick_launch.scss
> +$fasse-color: #DA6027;
site-specific

2022-01-06 19:36 UTC, adaybujeda commented
@whorka started working on a different approach.
Making the cluster banner a widget and including the widget based on the current cluster id.

I still need to make more changes to complete this approach, but I would like to discuss it with @whorka

2022-01-10 14:13 UTC, adaybujeda commented
I created an improved approach based on the custom configuration per cluster changes from issue https://github.com/hmdc/DevOpsProjects/issues/598

This approach uses the current configuration file created for the quick links in 598 to configure as well the welcome message.

2022-01-11 17:41 UTC, adaybujeda commented
Closing, changes added to #35

2022-01-11 17:41 UTC, closed without merging